// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRS2._0.Models.DataModels;

#nullable disable

namespace TRS2._0.Migrations
{
    [DbContext(typeof(TRSDBContext))]
    [Migration("20240813084659_AddAgreementEvent")]
    partial class AddAgreementEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.AffCodification", b =>
                {
                    b.Property<string>("Contract")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dist")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Affiliation")
                        .HasColumnType("int");

                    b.HasKey("Contract", "Dist");

                    b.ToTable("AffCodifications");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.AffHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AffId");

                    b.ToTable("AffHours");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Affiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Affiliations");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.AffxPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Exist")
                        .HasColumnType("bit");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AffId");

                    b.HasIndex("PersonId");

                    b.ToTable("AffxPersons");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.AgreementEvent", b =>
                {
                    b.Property<int>("AgreementEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgreementEventId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementEventId");

                    b.ToTable("AgreementEvents");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.DailyPMValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("PmPerDay")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("WorkableDays")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyPMValues");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Dedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End")
                        .HasColumnType("date");

                    b.Property<bool>("Exist")
                        .HasColumnType("bit");

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("PersId")
                        .HasColumnType("int");

                    b.Property<decimal>("Reduc")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersId");

                    b.ToTable("dedication");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Department", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_department_Id");

                    b.ToTable("department");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Leader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("LeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.HasKey("Id");

                    b.ToTable("Leaders");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Leave", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Day")
                        .HasColumnType("date")
                        .HasColumnName("Day")
                        .HasColumnOrder(1);

                    b.Property<decimal>("LeaveReduction")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("Legacy")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "Day");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Liqdayxproject", b =>
                {
                    b.Property<string>("LiqId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<int>("ProjId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Dedication")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("PMs")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("PersId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LiqId", "ProjId", "Day");

                    b.HasIndex("PersId");

                    b.HasIndex("ProjId");

                    b.ToTable("Liqdayxproject");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Liquidation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Dedication1")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Dedication2")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Destiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("date");

                    b.Property<int>("PersId")
                        .HasColumnType("int");

                    b.Property<string>("Project1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersId");

                    b.ToTable("Liquidations");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.NationalHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NationalHolidays");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.PersMonthEffort", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Month")
                        .HasColumnType("date")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PersonId", "Month");

                    b.ToTable("PersMonthEfforts");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Perseffort", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<DateTime>("Month")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("WpxPerson")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("PK_perseffort_Code");

                    b.HasIndex(new[] { "WpxPerson" }, "X4");

                    b.ToTable("perseffort");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("A3code")
                        .HasColumnType("int")
                        .HasColumnName("A3Code");

                    b.Property<int?>("Affiliation")
                        .HasColumnType("int");

                    b.Property<string>("BscId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PermissionLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<int?>("PersonnelGroup")
                        .HasColumnType("int");

                    b.Property<int>("Resp")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_personnel_Id");

                    b.HasIndex(new[] { "Department" }, "X1");

                    b.HasIndex(new[] { "Affiliation" }, "X2");

                    b.HasIndex(new[] { "Id", "BscId", "Name" }, "personnel$PersConstr")
                        .IsUnique()
                        .HasFilter("[BscId] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("personnel");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Personnelgroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Leader")
                        .HasColumnType("int");

                    b.Property<int?>("Leader2")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_personnelgroup_Id");

                    b.ToTable("personnelgroup");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Project", b =>
                {
                    b.Property<int>("ProjId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjId"));

                    b.Property<string>("Acronim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contract")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndReportDate")
                        .HasColumnType("date");

                    b.Property<int?>("Pi")
                        .HasColumnType("int")
                        .HasColumnName("PI");

                    b.Property<int?>("Pm")
                        .HasColumnType("int")
                        .HasColumnName("PM");

                    b.Property<string>("SType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sType");

                    b.Property<string>("SapCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("St1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("St2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<short?>("TpsCsic")
                        .HasColumnType("smallint")
                        .HasColumnName("TPsCSIC");

                    b.Property<short?>("TpsIcrea")
                        .HasColumnType("smallint")
                        .HasColumnName("TPsICREA");

                    b.Property<short?>("TpsUpc")
                        .HasColumnType("smallint")
                        .HasColumnName("TPsUPC");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Visible")
                        .HasColumnType("smallint");

                    b.HasKey("ProjId")
                        .HasName("PK_projects_ProjID");

                    b.HasIndex(new[] { "SapCode" }, "projects$ProjConstr")
                        .IsUnique()
                        .HasFilter("[SapCode] IS NOT NULL");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.ProjectMonthLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectMonthLocks");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Projectxperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Person")
                        .HasColumnType("int");

                    b.Property<int>("ProjId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_projectxperson_Id");

                    b.HasIndex(new[] { "ProjId" }, "pxp1");

                    b.HasIndex(new[] { "Person" }, "pxp2");

                    b.ToTable("projectxperson");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Projeffort", b =>
                {
                    b.Property<int>("Wp")
                        .HasColumnType("int")
                        .HasColumnName("WP");

                    b.Property<DateTime>("Month")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Wp", "Month");

                    b.HasIndex(new[] { "Wp" }, "X5");

                    b.ToTable("projeffort");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.ReportPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ProjId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProjId");

                    b.ToTable("ReportPeriods");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonnelId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PersonnelId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Timesheet", b =>
                {
                    b.Property<int>("WpxPersonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WpxPersonId", "Day");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Wp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Pms")
                        .HasColumnType("real")
                        .HasColumnName("PMs");

                    b.Property<int>("ProjId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_wp_Id");

                    b.HasIndex(new[] { "ProjId", "Name" }, "wp$ProjId")
                        .IsUnique();

                    b.ToTable("wp");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Wpxperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Person")
                        .HasColumnType("int");

                    b.Property<int>("Wp")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_wpxperson_Id");

                    b.HasIndex(new[] { "Wp" }, "wxp1");

                    b.HasIndex(new[] { "Person" }, "wxp2");

                    b.ToTable("wpxperson");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.AffHours", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Affiliation", "Affiliation")
                        .WithMany()
                        .HasForeignKey("AffId")
                        .IsRequired();

                    b.Navigation("Affiliation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.AffxPerson", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Affiliation", "Affiliation")
                        .WithMany()
                        .HasForeignKey("AffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "Personnel")
                        .WithMany("AffxPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliation");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Dedication", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "Pers")
                        .WithMany()
                        .HasForeignKey("PersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("dedication$deidcationx1");

                    b.Navigation("Pers");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Leave", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "PersonNavigation")
                        .WithMany("Leaves")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Leave_Personnel");

                    b.Navigation("PersonNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Liqdayxproject", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Liquidation", "Liquidation")
                        .WithMany("Liqdayxprojects")
                        .HasForeignKey("LiqId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "Personnel")
                        .WithMany("Liqdayxprojects")
                        .HasForeignKey("PersId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TRS2._0.Models.DataModels.Project", "Project")
                        .WithMany("Liqdayxprojects")
                        .HasForeignKey("ProjId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Liquidation");

                    b.Navigation("Personnel");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Liquidation", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "Personnel")
                        .WithMany("Liquidations")
                        .HasForeignKey("PersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.PersMonthEffort", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "PersonNavigation")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Perseffort", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Wpxperson", "WpxPersonNavigation")
                        .WithMany("Persefforts")
                        .HasForeignKey("WpxPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("perseffort$X4");

                    b.Navigation("WpxPersonNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Personnel", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Department", "DepartmentNavigation")
                        .WithMany("Personnel")
                        .HasForeignKey("Department")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("personnel$X1");

                    b.Navigation("DepartmentNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Projectxperson", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "PersonNavigation")
                        .WithMany("Projectxpeople")
                        .HasForeignKey("Person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("projectxperson$pxp2");

                    b.HasOne("TRS2._0.Models.DataModels.Project", "Proj")
                        .WithMany("Projectxpeople")
                        .HasForeignKey("ProjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("projectxperson$pxp1");

                    b.Navigation("PersonNavigation");

                    b.Navigation("Proj");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Projeffort", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Wp", "WpNavigation")
                        .WithMany()
                        .HasForeignKey("Wp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("projeffort$X5");

                    b.Navigation("WpNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.ReportPeriod", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Project", "Project")
                        .WithMany("ReportPeriods")
                        .HasForeignKey("ProjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "Personnel")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("TRS2._0.Models.DataModels.TRS2._0.Models.DataModels.ApplicationUser", "PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Timesheet", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Wpxperson", "WpxPersonNavigation")
                        .WithMany("Timesheets")
                        .HasForeignKey("WpxPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WpxPersonNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Wp", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Project", "Proj")
                        .WithMany("Wps")
                        .HasForeignKey("ProjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("wp$wp_ibfk_1");

                    b.Navigation("Proj");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Wpxperson", b =>
                {
                    b.HasOne("TRS2._0.Models.DataModels.Personnel", "PersonNavigation")
                        .WithMany("Wpxpeople")
                        .HasForeignKey("Person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("wpxperson$wxp2");

                    b.HasOne("TRS2._0.Models.DataModels.Wp", "WpNavigation")
                        .WithMany("Wpxpeople")
                        .HasForeignKey("Wp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("wpxperson$wxp1");

                    b.Navigation("PersonNavigation");

                    b.Navigation("WpNavigation");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Department", b =>
                {
                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Liquidation", b =>
                {
                    b.Navigation("Liqdayxprojects");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Personnel", b =>
                {
                    b.Navigation("AffxPersons");

                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("Leaves");

                    b.Navigation("Liqdayxprojects");

                    b.Navigation("Liquidations");

                    b.Navigation("Projectxpeople");

                    b.Navigation("Wpxpeople");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Project", b =>
                {
                    b.Navigation("Liqdayxprojects");

                    b.Navigation("Projectxpeople");

                    b.Navigation("ReportPeriods");

                    b.Navigation("Wps");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Wp", b =>
                {
                    b.Navigation("Wpxpeople");
                });

            modelBuilder.Entity("TRS2._0.Models.DataModels.Wpxperson", b =>
                {
                    b.Navigation("Persefforts");

                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
